package org.cybnity.infrastructure.technical.message_bus.adapter.impl.redis;

import static org.junit.Assert.assertEquals;

import org.cybnity.framework.Context;
import org.cybnity.framework.IContext;
import org.junit.Before;
import org.junit.Test;

import io.lettuce.core.RedisClient;
import io.lettuce.core.api.StatefulRedisConnection;
import io.lettuce.core.api.sync.RedisStringCommands;
import io.vertx.redis.client.RedisOptions;

/**
 * Unit test of RedisOptionsFactory behaviors regarding its supported
 * requirements.
 * 
 * @author olivier
 *
 */
public class RedisOptionFactoryCaseTest {

    private String connectionUserAccount, connectionPassword, serverHost, serverPort, databaseNumber,
	    defaultAuthPassword;

    private IContext ctx;

    @Before
    public void initRedisConnectionChainValues() {
	defaultAuthPassword = "1gEGHneiLT"; // Redis Kubernetes configuration's REDISCLI_AUTH environment variable
	serverHost = "localhost";
	serverPort = "6379"; // Default port
	databaseNumber = "1";// Default first db number
	connectionUserAccount = "default";
	connectionPassword = defaultAuthPassword;
	// Build reusable context
	this.ctx = new Context();
	ctx.addResource(defaultAuthPassword, "defaultAuthPassword", false);
	ctx.addResource(serverHost, "serverHost", false);
	ctx.addResource(serverPort, "serverPort", false);
	ctx.addResource(databaseNumber, "databaseNumber", false);
	ctx.addResource(connectionUserAccount, "connectionUserAccount", false);
	ctx.addResource(connectionPassword, "connectionPassword", false);
    }

    @Test
    public void givenManagedRedisClusterResources_whenCreateRedisOption_thenReadFromEnvironmentVariables()
	    throws Exception {
	// Define Redis connection and host variables
	RedisOptions options = RedisOptionFactory.createUsersInteractionsSpaceOptions(connectionUserAccount,
		connectionPassword, serverHost, serverPort, databaseNumber, connectionPassword);

	// Test Lettuce client (see https://lettuce.io/core/release/reference/index.html
	// for detail)
	RedisClient client = RedisClient.create(options.getEndpoint());
	StatefulRedisConnection<String, String> connection = client.connect();
	RedisStringCommands<String, String> sync = connection.sync();

	// Remove potential previous data versions generated by previous unit test
	// executions
	sync.getdel("mib1");
	sync.getdel("mib2");

	// Create records in database
	sync.append("mib1", "Agent J");
	sync.append("mib2", "Agent K");

	// Retrieve and check values
	assertEquals("Agent J", sync.get("mib1"));
	assertEquals("Agent K", sync.get("mib2"));

	connection.close();
	client.shutdown();
    }
}
