package org.cybnity.framework.domain;

import org.cybnity.framework.support.annotation.Requirement;
import org.cybnity.framework.support.annotation.RequirementCategory;

import java.util.Collection;

/**
 * Represent a denormalized read repository (also named Query Model) which
 * can subscribe to events on a write model. It's a component of the read side of
 * an application. Segregation elements of the CQRS pattern, this component is
 * responsible to expose readable different sets of classes to other systems
 * (e.g application user interface).
 * <br>
 * Typically, return data item over Data Transfer Objects (DTO) via queries.
 * <br>
 * The implementation system (e.g database) is optimized for reads by being
 * denormalized to suit the specific queries that an application should support
 * on the read side.
 * <br>
 * The returned data versions can be generated by Read Model Projections responsible to realize (through simple set of domain event subscribers hosted by the read-model) generation and update (e.g calculation of derived information, indexed and optimized search criteria ordering of DTO versions) of a persistent Read Model for later consumption.
 *
 * @author olivier
 */
@Requirement(reqType = RequirementCategory.Scalability, reqId = "REQ_SCA_4")
public interface IReadModel {

    /**
     * Get the projections supported by this read model.
     *
     * @return A collection of projections relative several types of queryable domain layer's entities and/or value objects exposed by the bounded context.
     */
    Collection<IReadModelProjection> projections();
}
