annotations:
  category: Database
  licenses: Apache-2.0
apiVersion: v2
appVersion: 7.0.8
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami
  tags:
  - bitnami-common
  version: 2.x.x
description: Redis(R) advanced key-value store of UI layer interactions.
# @Requirement(reqType = RequirementCategory.Maintainability, reqId = "REQ_MAIN_1")
home: https://github.com/bitnami/charts/tree/main/bitnami/redis
icon: https://bitnami.com/assets/stacks/redis/img/redis-stack-220x234.png
keywords:
- redis
- keyvalue
- database
maintainers:
- name: Bitnami
  url: https://github.com/bitnami/charts
name: redis
sources:
- https://github.com/bitnami/containers/tree/main/bitnami/redis
version: 17.7.3
