# Mandatory automatic build of java components before to manage a pull request
# that allow to detect valid compilation before to merge source codes via a pull request effort by a reviewer

name: Java components COMMIT STAGE

run-name: Unit testing & quality verification

on:
  pull_request:
    types: [opened, reopened]
    branches:
      - 'feature*'
      - 'hotfix*'
      - 'fix*'
      - 'dev*'
      - 'staging*'
      - 'integration*'

    # when changes detected on files or java sub-projects
    paths:
      - '**pom.xml'
      - 'implementations-line/**'
      - 'systems-line/**'

jobs:
  specific_review_requested:
    runs-on: ubuntu-latest
    #if: ${{ github.event.requested_team.name == 'octo-team'}}
    steps:
      - run: echo Review is requested from ${{ github.event.requested_team.name }}

  java_verify:
    name: Java components build
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step_verify.outputs.state }}

    permissions:
      contents: read
      #packages: write
      pull-requests: write
      #deployments: write

    steps:
      - name : Identify the branch of java project to build with Maven
        run: echo The branch to build is ${{ inputs.branch_name }}

      # Patch of workflow regarding save-state and set-output commands when not defined by user environment variable file
      #- name: Save state
      #  run: echo "{name}={value}" >> $GITHUB_STATE
      #- name: Set output
      #  run: echo "{name}={value}" >> $GITHUB_OUTPUT

      - name: Checkout source codes from origin branch
        uses: actions/checkout@v3
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          ref: ${{ inputs.branch_name }}

      - name: Set up java version for build (Temurin JDK)
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: maven
          # defined settings.xml values allowing Maven remote repository use
          server-id: space-cybnity-open-source
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD

      - name:  Verify the java packages quality (phases validate, compile, test, package, verify)
        id: step_verify
        run: mvn --batch-mode --update-snapshots --show-version --file pom.xml verify
        run: echo "::set-output name=state::SUCCESS"
        env:
            MAVEN_USERNAME: ${{ secrets.SPACE_CYBNITY_OS_REPO_USERNAME }}
            MAVEN_PASSWORD: ${{ secrets.SPACE_CYBNITY_OS_REPO_PASSWORD }}

  build_result:
    runs-on: ubuntu-latest
    needs: java_verify
    #if: ${{ github.event.requested_team.name == 'octo-team' }}
    steps:
      - run: echo Result of quality verification is a ${{ needs.java_verify.outputs.output1 }}
