# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Foundation modules build with Maven

run-name: Foundation COMMIT STAGE

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  java_build:
    name: Java Foundation Components Build
    
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
      pull-requests: write
      deployments: write
      
    steps:
    
    # Patch of workflow regarding save-state and set-output commands when nto defined by user environment variable file
    - name: Save state
      run: echo "{name}={value}" >> $GITHUB_STATE
      
    - name: Set output
      run: echo "{name}={value}" >> $GITHUB_OUTPUT
      
    - name: Checkout MAIN branch's source codes
      uses: actions/checkout@v3
      with:
        repository: ${{ github.repository }}
        token: ${{ github.token }}
        ref: main
        
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven
        server-id: space-cybnity-open-source
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
        
    - name: VALIDATION & COMPILING
      run: echo "VALIDATION & COMPILING"
      
    - name: UNIT TESTING
      run: echo "TESTING"
    
    - name: BINARY PACKAGING
      run: mvn --batch-mode package --file pom.xml
      
    - name: QUALITY VERIFICATION
      run: echo "QUALITY VERIFICATION"
    
    - name: LOCAL INSTALLATION
      run: echo "LOCAL INSTALLATION"
    
    - name: REMOTE INSTALLATION
      run: echo "REMOTE INSTALLATION"
    
    - name: Build, verify and install parent pom.xml into local repository
      run: mvn --batch-mode clean install -N -U --file pom.xml
      env:
          MAVEN_USERNAME: ${{ secrets.SPACE_CYBNITY_OS_REPO_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SPACE_CYBNITY_OS_REPO_PASSWORD }}

    # Optional: Uploads the full dependency graph to GitHub (output variable) to improve the quality of Dependabot alerts this repository can receive
    #- name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6

    - name: Build, package and publish parent pom.xml to CYBNITY Open Source projects repository
      run: mvn --batch-mode deploy --file pom.xml
      env:
          MAVEN_USERNAME: ${{ secrets.SPACE_CYBNITY_OS_REPO_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.SPACE_CYBNITY_OS_REPO_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
