# Automated archiving of source codes repository to Bitbucket remote backup instance
name: Project Assets Archiving
run-name: REPOSITORY ARCHIVING - Source codes backup
on:
  push:
    # execution when ...
    branches:
      - 'main'
      - 'integration'
      - 'staging'
  delete:
    # execution when ...
    branches:
      - 'main'
      - 'integration'
      - 'staging'

# The archiging stage workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mirror_repository_contents:
    name: Backup repository mirror to AWS S3
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
      - name: Read reusable environment variables
        uses: FranzDiebold/github-env-vars-action@v2

      - name: Checkout source codes from branch
        id: checkout_step
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          ref: ${{ inputs.branch_name }}
          fetch-depth: 0 # <-- clone with complete history

      # See https://github.com/aws-actions/configure-aws-credentials?tab=readme-ov-file#oidc-configuration-details
      # Get access to AWS resources using an IAM Role
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v6.1.0
        with:
          role-to-assume: '${{ secrets.AWS_S3_ROLE_ARCHIVER }}'
          aws-region: '${{ secrets.AWS_S3_BACKUP_BUCKET_REGION }}'
          output-credentials: true # reference the fetched credentials as outputs that allow to use the aws-session-token input in a situation where session tokens are fetched and passed to this action

      - name: Read caller identity connected over AWS Client
        run: |
          echo "AWS credentials and project variables read"
          echo "BRANCH_NAME=$CI_REF_NAME" >> $GITHUB_ENV
          echo "REPO=$CI_REPOSITORY" >> $GITHUB_ENV
          aws sts get-caller-identity

      # See doc at https://github.com/fredydlemus/s3-backup
      - name: Compress repository and store backup file into AWS S3 dedicated bucket
        uses: fredydlemus/s3-backup@v1
        with:
          target-bucket: '${{ secrets.AWS_S3_BACKUP_BUCKET }}/${{ env.REPO }}/${{ env.BRANCH_NAME }}' # Bucket name sub-folder (repo name based) where to store repository mirrored files (compressed backup as tar.gz file)
          bucket-region: '${{ secrets.AWS_S3_BACKUP_BUCKET_REGION }}' # The WAS region where the S3 bucket is located
          role-arn: '${{ secrets.AWS_S3_ROLE_ARCHIVER }}' # The ARN of the IAM role to assume for S3 access
          oidc-audience: '${{ secrets.AWS_IDENTITY_PROVIDER_GITHUB_OIDC_AUDIENCE }}' # The audience value for the OIDC token
          backup-prefix: '${{ env.BRANCH_NAME }}_branch_backup' # Prefix for the backup file name

