# Automated archiving of source codes repository to Bitbucket remote backup instance
name: Project Assets Archiving
run-name: ARCHIVING - Source codes backup refresh
on:
  push:
    # execution when ...
    branches:
      - 'feature*'
      - 'main'
      - 'integration'
      - 'staging'
  delete:
    # execution when ...
    branches:
      - 'feature*'
      - 'main'
      - 'integration'
      - 'staging'

# The archiging stage workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  mirror_repository_contents:
    name: Backup repository contents to Bitbucket
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Use variables
        run: |
          echo "repository variable : $REPOSITORY_VAR"
          echo "organization variable : $ORGANIZATION_VAR"
        env:
          REPOSITORY_VAR: ${{ github.repository }}
          ORGANIZATION_VAR: ${{ github.repository_owner }}

      - name: Checkout source codes from branch
        id: checkout_step
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          token: ${{ github.token }}
          ref: ${{ inputs.branch_name }}
          fetch-depth: 0 # <-- clone with complete history

      - name: Push contents of ${{ github.repository }} to Bitbucket repository
        uses: heussd/mirror-to-bitbucket-github-action@v2
        with:
            username: olivier_lemee
            spacename: agnet
            repository: foundation
            password: ${{ secrets.BITBUCKET_APP_PASSWORD }}
        env:
            REPOSITORY_NAME: ${{ github.repository }}
